spring:
    application:
        name: "Metrics"

management:
    endpoints:
        web:
            exposure:
                include: "*"
    prometheus:
        metrics:
            export:
                enabled: true

server:
    port: 8080